FROM oven/bun:1.3.2-alpine AS dev
WORKDIR /app

# Install dependencies
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

# Copy source (volumes will override in docker-compose)
COPY src ./src
COPY tsconfig.json build.ts ./

EXPOSE 3000
CMD ["bun", "--watch", "--hot", "src/index.ts"]
